on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed
    branches:
      - master

concurrency: 
  group: production
  cancel-in-progress: true

steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}